# version.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymp-redis-readonly
  namespace: pymp
spec:
  template:
    spec:
      containers:
        - name: pymp-redis-readonly
          image: redis:latest
          imagePullPolicy: Always