apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pymp-server-ffmpeg
    pymp.image: pymp-server
  name: pymp-server-ffmpeg
  namespace: pymp
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pymp-server-ffmpeg
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: pymp-server-ffmpeg
        redis: readwrite
    spec:
      containers:
      - name: pymp-server
        image: ghcr.io/tomp736/pymp/pymp_server:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: pymp-server-ffmpeg
        volumeMounts:
          - name: config-volume
            mountPath: /app/services_config.json
            subPath: services_config.json
      volumes:
        - name: config-volume
          configMap:
            name: services-config