apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pymp-server-ffmpeg
  name: pymp-server-ffmpeg
  namespace: pymp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pymp-server-ffmpeg
  template:
    metadata:
      labels:
        app: pymp-server-ffmpeg
        redis: readwrite
    spec:
      containers:
      - name: pymp-server-ffmpeg
        image: ghcr.io/tomp736/pymp/pymp_server:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pymp-server-ffmpeg