apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pymp-server-ffmpeg
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pymp-server-ffmpeg
  targetCPUUtilizationPercentage: 50