apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tpisula
resources:  
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  # - resources/ingress.yaml
patches:
  - patches/version.patch.yaml