apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pymp_redis
  - pymp_redis_readonly
  - pymp_frontend
  - pymp_server_media_registry
  - pymp_server_media
  - pymp_server
  - pymp_prometheus