apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pymp
resources:
  - namespace.yaml
  - configmap.services.yaml
  - pymp_redis
  - pymp_redis_readonly
  - pymp_frontend
  - pymp_server_media_registry
  - pymp_server_ffmpeg
  - pymp_server_media
  - pymp_server
  - pymp_prometheus
patches:
  - path: patches/pymp_frontend.version.patch.yaml
    target:
      labelSelector: "pymp.image=pymp-frontend"
  - path: patches/pymp_server.version.patch.yaml
    target:
      labelSelector: "pymp.image=pymp-server"