apiVersion: v1
kind: ConfigMap
metadata:
  name: pymp-server-media-registry
  namespace: pymp
data:
  PYTHONHASHSEED: "383747829"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "80"
  
  REDIS_HOST: "pymp-redis"
  REDIS_PORT: "6379"

  SERVER_PROTO: "http"
  SERVER_HOST: "pymp-server-media-registry"
  SERVER_PORT: "80"
  SERVER_TYPE: "32"