# version.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymp-prometheus
  namespace: pymp
spec:
  template:
    spec:
      containers:
        - name: pymp-prometheus
          image: prom/prometheus
          imagePullPolicy: Always