apiVersion: v1
kind: ConfigMap
metadata:
  name: pymp-server-media
  namespace: pymp
data:
  PYTHONHASHSEED: "383747829"

  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "80"
  FLASK_CORS_HEADER: "http://frontend.pymp.labrats.work"
  
  REDIS_HOST: "pymp-redis-readonly"
  REDIS_PORT: "6379"

  MEDIA_MEDIA_CHUNK_SIZE: "4194304"
  MEDIA_THUMB_CHUNK_SIZE: "32768"

  SERVER_PROTO: "http"
  SERVER_HOST: "pymp-server-media"
  SERVER_PORT: "80"
  SERVER_ROLES: "16"