apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pymp-server-media
    pymp.image: pymp-server
  name: pymp-server-media
  namespace: pymp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pymp-server-media
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: pymp-server-media
        redis: readonly
    spec:
      containers:
      - name: pymp-server
        image: ghcr.io/tomp736/pymp/pymp_server:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pymp-server-media
        env:
        - name: SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /app/registry-services.json
            subPath: registry-services.json
      volumes:
        - name: config-volume
          configMap:
            name: pymp-registry-services