apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik-public
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 20.8.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingressClass:
      enabled: true
      isDefaultClass: false

    ingressRoute:
      dashboard:
        enabled: false 

    ports:
      web:
        nodePort: 32080

      websecure:
        nodePort: 32443