apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pymp
resources:  
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/configmap.yaml
  - resources/ingress.yaml