apiVersion: v1
kind: ConfigMap
metadata:
  name: pymp-server
  namespace: pymp
data:
  PYTHONHASHSEED: "383747829"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "80"
  REDIS_HOST: "pymp-redis-readonly"
  REDIS_PORT: "6379"
  MEDIA_CHUNK_SIZE: "4194304"
  THUMB_CHUNK_SIZE: "32768"
  CORS_HEADER: "http://frontend.pymp.labrats.work"

  SERVER_ID: "internal"
  SERVER_PROTO: "http"
  SERVER_HOST: "pymp-server"
  SERVER_PORT: "80"
  SERVER_TYPE: "15"

  MEDIAREGISTRY_SVC_PROTO: "http"
  MEDIAREGISTRY_SVC_HOST: "pymp-server-media-registry"
  MEDIAREGISTRY_SVC_PORT: "80"