# version.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymp-frontend
  namespace: pymp
spec:
  template:
    spec:
      containers:
        - name: pymp-frontend
          image: ghcr.io/tomp736/pymp/pymp_frontend:latest
          imagePullPolicy: Always