apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-default
spec:
  releaseName: metrics-default
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.8.3
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP
    rbac:
      create: true
    serviceAccount:
      create: true