# version.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymp-server
  namespace: pymp
spec:
  template:
    spec:
      containers:
        - name: pymp-server
          image: ghcr.io/tomp736/pymp/pymp_server:0.2.12-dev
          imagePullPolicy: Always