name: Update PyMP Patch
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-pymp-patch]

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}

    steps:      
      # Read the current version number from git ls-remote
      - id: current_version
        shell: bash
        run: |
          echo "version=$(git ls-remote --tag origin | cut -d '/' -f 3 | sort -V | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)" >> $GITHUB_OUTPUT

  update-patches:
    needs: 
      - prepare
    strategy:
      fail-fast: false
      matrix:
        image:
          - pymp_frontend
          - pymp_server
          
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check image manifest
        run: |
          docker manifest inspect ghcr.io/tomp736/pymp/${{ matrix.image }}:${{ needs.prepare.outputs.current_version }}
      
      - name: Update deployment images
        run: |
          yq e '.spec.template.spec.containers[0].image = "ghcr.io/tomp736/pymp/${{ matrix.image }}:${{ needs.prepare.outputs.current_version }}"' -i applications/pymp/patches/${{ matrix.image }}.version.patch.yaml
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: patches
          path: applications/pymp/patches
          retention-days: 1

  commit-patches:
    needs: 
      - update-patches

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: patches
          path: applications/pymp/patches
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - run: |
          for file in applications/pymp/patches/*; 
          do 
            echo "Adding $file"
            cat $file
            git add $file
          done
          
      - run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected"
            git commit -am "updating patches"
            git push
          else
            echo "No changes detected"
          fi