name: Update PyMP Patch
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}

    steps:      
      # Read the current version number from git ls-remote
      - id: current_version
        shell: bash
        run: |
          echo "version=$(git ls-remote --tag https://github.com/tomp736/pymp.git | cut -d '/' -f 3 | sort -V | tail -1)" >> $GITHUB_OUTPUT      

  update-patches:
    needs: 
      - prepare
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/tomp736/pymp/pymp_frontend
          - ghcr.io/tomp736/pymp/pymp_server
          
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if image is available
        run: |
          docker pull ${{ matrix.image }}:${{ needs.prepare.outputs.current_version }}-dev
      
      - name: Update deployment images
        if: matrix.image == 'ghcr.io/tomp736/pymp/pymp_frontend'
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ matrix.image }}:${{ needs.prepare.outputs.current_version }}-dev"' -i applications/pymp/patches/pymp-frontend.version.patch.yaml
      
      - name: Update deployment images
        if: matrix.image == 'ghcr.io/tomp736/pymp/pymp_server'
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ matrix.image }}:${{ needs.prepare.outputs.current_version }}-dev"' -i applications/pymp/patches/pymp-server.version.patch.yaml

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: patches
          path: applications/pymp/patches
          retention-days: 1

  commit-patches:
    needs: 
      - update-patches

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: patches
          path: applications/pymp/patches
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "updating patches"
          git push