apiVersion: v1
kind: ConfigMap
metadata:
  name: pymp-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: 
            - 'pymp-prometheus:9090'

      - job_name: 'pymp'
        static_configs:
          - targets:
            - 'pymp-server:8000'
            - 'pymp-server-media:8000'
            - 'pymp-server-ffmpeg:8000'
            - 'pymp-server-media-registry:8000'
