apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pymp-prometheus
  name: pymp-prometheus
  namespace: pymp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pymp-prometheus
  template:
    metadata:
      labels:
        app: pymp-prometheus
    spec:
      containers:
      - name: pymp-prometheus
        image: prom/prometheus
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /app/services_config.json
            subPath: services_config.json
      volumes:
        - name: config-volume
          configMap:
            name: services-config