apiVersion: v1
kind: Service
metadata:
  name: pymp-prometheus
  namespace: pymp
  labels:
    app: pymp-prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: pymp-prometheus